### ISSUE TITLE
Auth with developer account. Is this plugin dead?

### ISSUE THREAD

**Issue by Lostrick** [ETdoFresh/FishyEOS#6]
How do you connect with developer account? I've set up the developer tools and I've tried many ways to connect but can't seem to get it working, am I doing something wrong? what should I choose here? Is this still working?
![image](https://user-images.githubusercontent.com/8244554/236911787-424b59ad-9b44-4b70-896a-fa6f07ab77ef.png)

**Comment by pgagne89** [comment]
I had a lot of issues setting it up as well, but got it working after a while. Here are a couple of things you can check:

1. Check the warnings in your logs. A lot of the errors are logged as warnings instead of errors.
2. Use "Epic" as external credential type instead of "Epic Id Token".
3. Leave the "Display Name" blank. EOS doesn't allow a display name when using an account.
4. Make sure you have linked your game client in the epic games admin.

**Comment by FirstGearGames** [comment]
Closing to not mislead future users with title.
